### ISSUE TITLE
Exception when looking for CODE BEGINS (0.4.7)

### ISSUE THREAD

**Issue by levkowetz** [xym-tool/xym#35]
In xym 0.4.7, the loop that looks for \<CODE BEGINS> can run out of content and raise an exception:

  
  $ xym /www/tools.ietf.org/rfc/rfc8489.txt 
  Traceback (most recent call last):
    File "/home/henrik/src/db/trunk/trunk37/bin/xym", line 92, in \<module>
      run()
    File "/home/henrik/src/db/trunk/trunk37/bin/xym", line 55, in run
      force_revision_regexp=args.force_revision_regexp)
    File "/home/henrik/src/db/trunk/trunk37/lib/python3.7/site-packages/xym/xym.py", line 579, in xym
      ye.extract_yang_model(sf.readlines())
    File "/home/henrik/src/db/trunk/trunk37/lib/python3.7/site-packages/xym/xym.py", line 503, in extract_yang_model
      line = line[:-1] + content[i+1].strip(' ')
  IndexError: list index out of range

**Comment by levkowetz** [comment]
Additionally, downgrading to 0.4.4 instead runs into an issue that non-ascii drafts triggers an exception:

   $ xym /a/www/ietf-ftp/internet-drafts/draft-sheffer-uta-bcp195bis-00.txt 
  Traceback (most recent call last):
    File "/a/www/ietf-datatracker/6.118.0/env/bin/xym", line 92, in <module>
      run()
    File "/a/www/ietf-datatracker/6.118.0/env/bin/xym", line 55, in run
      force_revision_regexp=args.force_revision_regexp)
    File "/a/www/ietf-datatracker/6.118.0/env/lib64/python3.6/site-packages/xym/xym.py", line 571, in xym
      ye.extract_yang_model(sf.readlines())
    File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4119: ordinal not in range(128)

This raises the urgency of resolving the CODE BEGINS loop exception.

**Comment by einarnn** [comment]
@levkowetz, do you have a suggested fix for 0.4.7? Happy to review a pull request and facilitate a new release, but do not have time right now to look at fixing this.

**Comment by levkowetz** [comment]
@einarnn: Sure.  PR https://github.com/xym-tool/xym/pull/36 submitted.

**Comment by einarnn** [comment]
New version released to pypi, 0.4.8.
